### ISSUE TITLE
apache24 url not found

### ISSUE THREAD

**Issue by JomaKar** [djl/homebrew-apache2#28]
when typing  brew install djl/apache2/apache24 into terminal i got the next mistake: curl: (22) The requested URL returned error: 404 Not Found
Error: Failed to download resource "apache24"
Download failed: http://mirror.cc.columbia.edu/pub/software/apache/httpd/httpd-2.4.18.tar.gz

**Comment by JomaKar** [comment]
if the url would've be  http://mirror.cc.columbia.edu/pub/software/apache/httpd/httpd-2.4.20.tar.gz
instead of  http://mirror.cc.columbia.edu/pub/software/apache/httpd/httpd-2.4.18.tar.gz it would work. However, don't know if it would work if i fork the project and change it on my copy. perhaps, i'll check out

**Comment by djl** [comment]
Fixed in 7aa4babb1e0b6cbd6f07b032b3b86792a5d88147.

Apache's mirrors are super annoying. As soon as a new version is released the old tarballs are archived. I should probably just use the archive URLs permanently but that means not using a mirror which I'm not keen on.

Meh I'll figure something out.

**Comment by JomaKar** [comment]
I tried my self, cloning in a new repo, but don't understand where is the wrong url wrote, looks like you do it dynamically. Can't solve it. is it, just by now, an easy way to change the wrong url?
